### ISSUE TITLE
`tmpdir` module should be required first when using Ruby 2.3.1

### ISSUE THREAD

**Issue by EvianZhow** [Instabug/instabug-reactnative#117]
```
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/atomos-0.1.1/lib/atomos.rb:8:in `atomic_write': undefined method `tmpdir' for Dir:Class (NoMethodError)
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/xcodeproj-1.5.5/lib/xcodeproj/project.rb:354:in `save'
	from ./node_modules/instabug-reactnative/link.rb:79:in `<main>'
```

Fixed according to similar steps: https://github.com/ydkn/capistrano-git-copy/issues/22

**Comment by ZiadAyman** [comment]
Thanks @EvianZhow for pointing this out. We'll be adding it to our docs :)
