### ISSUE TITLE
Calling Instabug.disable() in JS crashes Android app

### ISSUE THREAD

**Issue by cpetzel** [Instabug/instabug-reactnative#128]
The internal `disable()` method in the SDK is executing on a background thread, and its trying to touch views, so Android will complain. 

```
Accessibility content change on non-UI thread. Future Android versions will throw an exception.
                                                                       android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
                                                                           at android.view.ViewRootImpl$SendWindowContentChangedAccessibilityEvent.runOrPost(ViewRootImpl.java:7936)
                                                                           at android.view.ViewRootImpl.postSendWindowContentChangedCallback(ViewRootImpl.java:7047)
                                                                           at android.view.ViewRootImpl.notifySubtreeAccessibilityStateChanged(ViewRootImpl.java:7230)
                                                                           at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:3593)
                                                                           at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:3593)
                                                                           at android.view.View.notifyViewAccessibilityStateChangedIfNeeded(View.java:11221)
                                                                           at android.view.View.onFocusChanged(View.java:6936)
                                                                           at android.view.View.clearFocusInternal(View.java:6796)
                                                                           at android.view.View.unFocus(View.java:6829)
                                                                           at android.view.ViewGroup.unFocus(ViewGroup.java:1093)
                                                                           at android.view.ViewGroup.removeViewInternal(ViewGroup.java:5229)
                                                                           at android.view.ViewGroup.removeViewInternal(ViewGroup.java:5216)
                                                                           at android.view.ViewGroup.removeView(ViewGroup.java:5147)
                                                                           at com.instabug.library.invocation.a.b.c(FloatingButtonInvoker.java:157)
                                                                           at com.instabug.library.invocation.a.b.b(FloatingButtonInvoker.java:68)
                                                                           at com.instabug.library.invocation.b.g(InvocationManager.java:154)
                                                                           at com.instabug.library.a.x(InstabugDelegate.java:345)
                                                                           at com.instabug.library.a.g(InstabugDelegate.java:324)
                                                                           at com.instabug.library.Instabug.disable(Instabug.java:903)
                                                                           at com.instabug.reactlibrary.RNInstabugReactnativeModule.disable(RNInstabugReactnativeModule.java:564)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
```

The disable method in Android should simply post a runnable on the main thread

**Comment by Korazy** [comment]
Hey @cpetzel, thanks for reporting this issue. We'll try to get it fixed as soon as possible!

**Comment by Korazy** [comment]
@cpetzel apologies for the delay. This should be resolved in the latest release.
