### ISSUE TITLE
Release 2.9.0: java.io.IOException: Duplicate zip entry [android/support/design/widget/CoordinatorLayout$1.class]

### ISSUE THREAD

**Issue by Sammekl** [Instabug/instabug-reactnative#145]
Hi,

Our project automatically upgraded to the new `instabug-reactnative` release `2.9.0` this caused an issue during proguard obfuscation:

```
Caused by: java.io.IOException: Can't write [/Users/vagrant/git/our-app/android/app/build/intermediates/transforms/proguard/acceptance/0.jar] 
(Can't read [/Users/vagrant/git/our-app/android/app/build/intermediates/transforms/FirebasePerformancePlugin/acceptance/36(;;;;;;**.class)] (Can't read [android] 
(Can't read [support] (Can't read [design] (Can't read [widget] 
(Can't read [CoordinatorLayout$1.class] (Duplicate zip entry [android/support/design/widget/CoordinatorLayout$1.class])))))))
        at proguard.OutputWriter.writeOutput(OutputWriter.java:187)
        at proguard.OutputWriter.execute(OutputWriter.java:79)
        at proguard.ProGuard.writeOutput(ProGuard.java:427)
        at proguard.ProGuard.execute(ProGuard.java:175)
        at com.android.build.gradle.internal.transforms.BaseProguardAction.runProguard(BaseProguardAction.java:61)
        at com.android.build.gradle.internal.transforms.ProGuardTransform.doMinification(ProGuardTransform.java:253)
        at com.android.build.gradle.internal.transforms.ProGuardTransform.access$000(ProGuardTransform.java:63)
        at com.android.build.gradle.internal.transforms.ProGuardTransform$1.run(ProGuardTransform.java:173)
        at com.android.builder.tasks.Job.runTask(Job.java:47)
        at com.android.build.gradle.tasks.SimpleWorkQueue$EmptyThreadContext.runTask(SimpleWorkQueue.java:41)
        at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:282)
```

Downgrading to `2.8.1` or `2.8.0` resolves this issue

We are including this dependency using yarn and react-native-link and therefore are not in control of included dependencies. Do you have any solution for this issue, or is this something on your end that needs to be resolved?

**Comment by salmatarzi** [comment]
Can you please try cleaning and rebuilding again your project?

**Comment by salmatarzi** [comment]
Did you try to install this version on another sample project and it didn't work?

**Comment by Sammekl** [comment]
Yes, it depends if you are using the support library or not. This is still an issue on 2.10.0

**Comment by salmatarzi** [comment]
Can you please send us a sample app that has this error on contactus@instabug.com, to be able to debug this further?

**Comment by Sammekl** [comment]
I wanted to use your sample project but the project seems to be broken. I'm getting the following error while building:

`InstabugSample/node_modules/instabug-reactnative/android/build/intermediates/bundles/release/R.txt (No such file or directory)`

**Comment by Sammekl** [comment]
I found the issue in your code. You are not excluding the com.android.support group with module 'design' in your build.gradle.

Any chance this will be fixed soon? This project is unusable when your app relies on support design package..

**Comment by Korazy** [comment]
@Sammekl is this issue fixed for you? I will close it for now, if it's still ongoing, please feel free to reopen it.
