### ISSUE TITLE
2.12.0 java.lang.NullPointerException: Attempt to invoke virtual method 'void com.instabug.library.e.d()' on a null object reference

### ISSUE THREAD

**Issue by peacechen** [Instabug/instabug-reactnative#160]
Getting this error with the current Instabug RN library on Android (v2.12.0):
```
06-01 09:55:11.596 16817-16817/com.mycompany.myapp E/AndroidRuntime: FATAL EXCEPTION: main
   Process: com.mycompany.myapp, PID: 16817
   java.lang.RuntimeException: Unable to resume activity {com.mycompany.myapp/com.mycompany.myapp.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.instabug.library.e.d()' on a null object reference
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3103)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3134)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2481)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5417)
       at java.lang.reflect.Method.invoke(Native Method)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
    Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.instabug.library.e.d()' on a null object reference
       at com.instabug.library.tracking.a.onActivityResumed(InstabugActivityLifecycleListener.java:30)
       at android.app.Application.dispatchActivityResumed(Application.java:214)
       at android.app.Activity.onResume(Activity.java:1207)
       at com.facebook.react.ReactActivity.onResume(ReactActivity.java:63)
       at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1258)
       at android.app.Activity.performResume(Activity.java:6312)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3092)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3134) 
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2481) 
       at android.app.ActivityThread.-wrap11(ActivityThread.java) 
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
       at android.os.Handler.dispatchMessage(Handler.java:102) 
       at android.os.Looper.loop(Looper.java:148) 
       at android.app.ActivityThread.main(ActivityThread.java:5417) 
       at java.lang.reflect.Method.invoke(Native Method) 
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
```

**Comment by Korazy** [comment]
Hey @peacechen 

Thanks for reporting this, is this on the latest version of our RN SDK?

**Comment by Korazy** [comment]
Hey @peacechen 

We have a fix planned for this in next weeks release. Please let me know if you would like a custom build until then.

**Comment by peacechen** [comment]
Thanks for the update @Korazy .  No rush, I can use the prior version for now.

**Comment by sebirdman** [comment]
I just hit this as well. 

Any update on when the fix will be in?

**Comment by watadarkstar** [comment]
I also have this issue, I submitted a report to instabug via Intercom. Please notify us when this is fixed @Korazy !

**Comment by Korazy** [comment]
Hey @watadarkstar @sebirdman @peacechen

This should be resolved in 2.13.2, do you still face the issue there?

**Comment by abrel** [comment]
I do on 2.13.2
```
Fatal Exception: java.lang.RuntimeException
Unable to start activity ComponentInfo{com.karmamobile/com.instabug.library.invocation.invocationdialog.InstabugDialogActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.instabug.library.settings.a.n()' on a null object reference
```

**Comment by sebirdman** [comment]
@Korazy this is fixed for me now i think. haven't seen it.

**Comment by Korazy** [comment]
Awesome, I'm happy to hear that :)

**Comment by watadarkstar** [comment]
Same @sebirdman @Korazy this is fixed for me. Thanks for the fix 💯
