### ISSUE TITLE
(android) NoClassDefFoundError: com.instabug.library.analytics.AnalyticsObserver

### ISSUE THREAD

**Issue by SudoPlz** [Instabug/instabug-reactnative#90]
Hey there,

the app crashes whenever I try to launch it because of:

```
E/AndroidRuntime: FATAL EXCEPTION: main
                  java.lang.NoClassDefFoundError: com.instabug.library.analytics.AnalyticsObserver$1
                      at com.instabug.library.analytics.AnalyticsObserver.<init>(AnalyticsObserver.java:46)
                      at com.instabug.library.analytics.AnalyticsObserver.getInstance(AnalyticsObserver.java:58)
                      at com.instabug.library.Instabug$Builder.setInvocationEvent(Instabug.java:1711)
                      at com.instabug.reactlibrary.RNInstabugReactnativePackage.<init>(RNInstabugReactnativePackage.java:57)
                      at com.instabug.reactlibrary.RNInstabugReactnativePackage.<init>(RNInstabugReactnativePackage.java:69)
                      at com.acuityscheduling.app.android.MainApplication.createAdditionalReactPackages(MainApplication.java:78)
                      at com.reactnativenavigation.react.NavigationReactGateway$ReactNativeHostImpl.getPackages(NavigationReactGateway.java:132)
                      at com.facebook.react.ReactNativeHost.createReactInstanceManager(ReactNativeHost.java:74)
                      at com.reactnativenavigation.react.NavigationReactGateway$ReactNativeHostImpl.createReactInstanceManager(NavigationReactGateway.java:155)
                      at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:41)
                      at com.reactnativenavigation.react.NavigationReactGateway.getReactInstanceManager(NavigationReactGateway.java:59)
                      at com.reactnativenavigation.react.NavigationReactGateway.hasStartedCreatingContext(NavigationReactGateway.java:46)
                      at com.reactnativenavigation.controllers.SplashActivity.onResume(SplashActivity.java:28)
                      at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1184)
                      at android.app.Activity.performResume(Activity.java:5082)
                      at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2565)
                      at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2603)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2089)
                      at android.app.ActivityThread.access$600(ActivityThread.java:130)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1195)
                      at android.os.Handler.dispatchMessage(Handler.java:99)
                      at android.os.Looper.loop(Looper.java:137)
                      at android.app.ActivityThread.main(ActivityThread.java:4745)
                      at java.lang.reflect.Method.invokeNative(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:511)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
                      at dalvik.system.NativeStart.main(Native Method)
```

I'm using "instabug-reactnative": "2.0.11"

**Comment by NadineMansour** [comment]
Thank you @SudoPlz for sending this over. 
The team is looking into. 
I will keep you posted.

**Comment by SudoPlz** [comment]
More info:

That's on a Google Nexus S on **Android 4.1.1** API 16,
I tried running the same code on a Google Nexus 5x on **Android 8.0.0** and I didn't receive a crash.

**Comment by NadineMansour** [comment]
@SudoPlz Thank you for the valuable information.

**Comment by SudoPlz** [comment]
https://github.com/Instabug/instabug-reactnative/commits/customBuild/fix_no_class_def_crash fixed the issue above, but I know get this error:

```
FATAL EXCEPTION: main
                                                                                java.lang.NoClassDefFoundError: rx.subjects.PublishSubject
                                                                                    at com.instabug.library.core.eventbus.a.<init>(EventBus.java:16)
                                                                                    at com.instabug.library.core.eventbus.b.<init>(SessionStateEventBus.java:5)
                                                                                    at com.instabug.library.core.eventbus.b.a(SessionStateEventBus.java:11)
                                                                                    at com.instabug.library.invocation.b.m(InvocationManager.java:511)
                                                                                    at com.instabug.library.invocation.b.<init>(InvocationManager.java:75)
                                                                                    at com.instabug.library.invocation.b.a(InvocationManager.java:81)
                                                                                    at com.instabug.library.f.t(InstabugDelegate.java:244)
                                                                                    at com.instabug.library.f.b(InstabugDelegate.java:190)
                                                                                    at com.instabug.library.f.a(InstabugDelegate.java:171)
                                                                                    at com.instabug.library.Instabug$Builder.build(Instabug.java:2382)
                                                                                    at com.instabug.library.Instabug$Builder.build(Instabug.java:2431)
                                                                                    at com.instabug.reactlibrary.RNInstabugReactnativePackage.<init>(RNInstabugReactnativePackage.java:59)
                                                                                    at com.instabug.reactlibrary.RNInstabugReactnativePackage.<init>(RNInstabugReactnativePackage.java:69)
                                                                                    at com.acuityscheduling.app.android.MainApplication.createAdditionalReactPackages(MainApplication.java:83)
                                                                                    at com.reactnativenavigation.react.NavigationReactGateway$ReactNativeHostImpl.getPackages(NavigationReactGateway.java:132)
                                                                                    at com.facebook.react.ReactNativeHost.createReactInstanceManager(ReactNativeHost.java:74)
                                                                                    at com.reactnativenavigation.react.NavigationReactGateway$ReactNativeHostImpl.createReactInstanceManager(NavigationReactGateway.java:155)
                                                                                    at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:41)
                                                                                    at com.reactnativenavigation.react.NavigationReactGateway.getReactInstanceManager(NavigationReactGateway.java:59)
                                                                                    at com.reactnativenavigation.react.NavigationReactGateway.hasStartedCreatingContext(NavigationReactGateway.java:46)
                                                                                    at com.reactnativenavigation.controllers.SplashActivity.onResume(SplashActivity.java:28)
                                                                                    at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1184)
                                                                                    at android.app.Activity.performResume(Activity.java:5082)
                                                                                    at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2565)
                                                                                    at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2603)
                                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2089)
                                                                                    at android.app.ActivityThread.access$600(ActivityThread.java:130)
                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1195)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                    at android.os.Looper.loop(Looper.java:137)
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:4745)
                                                                                    at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                    at java.lang.reflect.Method.invoke(Method.java:511)
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
                                                                                    at dalvik.system.NativeStart.main(Native Method)
```

I believe it's easy to reproduce, all you have to do is start a Genymotion vm and use a `Google Nexus S - 4.1.1 - API 16 480x800` w/ 1 Processor, and 512MB base memory and you should be able to reproduce this.

**Comment by NadineMansour** [comment]
@SudoPlz I will check this and get back to you 😊

**Comment by NadineMansour** [comment]
@SudoPlz We have tried the same configurations and steps that you mentioned. However, we failed to reproduce the same crash.

Are you able to reproduce it on a real device or on the emulator?

**Comment by SudoPlz** [comment]
Ι'll try tomorrow and I'll post back @NadineMansour :)

**Comment by NadineMansour** [comment]
@SudoPlz Did you get a chance to try it?

**Comment by SudoPlz** [comment]
I did @NadineMansour, I get the [same errror](https://github.com/Instabug/instabug-reactnative/issues/90#issuecomment-343521711) on a Nexus S API 16 emulator.

**Comment by NadineMansour** [comment]
@SudoPlz Thank you for the details. 
We will look into it. 
I will keep you updated.

**Comment by messense** [comment]
Same issue.

```
11-17 10:34:22.370 20264 20264 E AndroidRuntime: FATAL EXCEPTION: main
11-17 10:34:22.370 20264 20264 E AndroidRuntime: Process: com.riskstorm.riskstorm, PID: 20264
11-17 10:34:22.370 20264 20264 E AndroidRuntime: java.lang.NoClassDefFoundError: com.instabug.library.analytics.AnalyticsObserver$1
11-17 10:34:22.370 20264 20264 E AndroidRuntime: at com.instabug.library.analytics.AnalyticsObserver.<init>(AnalyticsObserver.java:46)
11-17 10:34:22.370 20264 20264 E AndroidRuntime: at com.instabug.library.analytics.AnalyticsObserver.getInstance(AnalyticsObserver.java:58)
11-17 10:34:22.370 20264 20264 E AndroidRuntime: at com.instabug.library.Instabug$Builder.setInvocationEvent(Instabug.java:1711)
11-17 10:34:22.370 20264 20264 E AndroidRuntime: at com.instabug.reactlibrary.RNInstabugReactnativePackage.<init>(RNInstabugReactnativePackage.java:57)
11-17 10:34:22.370 20264 20264 E AndroidRuntime: at com.instabug.reactlibrary.RNInstabugReactnativePackage.<init>(RNInstabugReactnativePackage.java:69)
11-17 10:34:22.370 20264 20264 E AndroidRuntime: at com.riskstorm.riskstorm.MainApplication.createAdditionalReactPackages(MainApplication.java:42)
11-17 10:34:22.370 20264 20264 E AndroidRuntime: at com.reactnativenavigation.react.NavigationReactGateway$ReactNativeHostImpl.getPackages(NavigationReactGateway.java:132)
11-17 10:34:22.370 20264 20264 E AndroidRuntime: at com.facebook.react.ReactNativeHost.createReactInstanceManager(ReactNativeHost.java:76)
11-17 10:34:22.370 20264 20264 E AndroidRuntime: at com.reactnativenavigation.react.NavigationReactGateway$ReactNativeHostImpl.createReactInstanceManager(NavigationReactGateway.java:155)
11-17 10:34:22.370 20264 20264 E AndroidRuntime: at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:42)
11-17 10:34:22.370 20264 20264 E AndroidRuntime: at com.reactnativenavigation.react.NavigationReactGateway.getReactInstanceManager(NavigationReactGateway.java:59)
11-17 10:34:22.370 20264 20264 E AndroidRuntime: at com.reactnativenavigation.react.NavigationReactGateway.hasStartedCreatingContext(NavigationReactGateway.java:46)
11-17 10:34:22.370 20264 20264 E AndroidRuntime: at com.reactnativenavigation.controllers.SplashActivity.onResume(SplashActivity.java:42)
11-17 10:34:22.370 20264 20264 E AndroidRuntime: at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1192)
11-17 10:34:22.370 20264 20264 E AndroidRuntime: at android.app.Activity.performResume(Activity.java:5317)
11-17 10:34:22.370 20264 20264 E AndroidRuntime: at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2787)
11-17 10:34:22.370 20264 20264 E AndroidRuntime: at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2825)
11-17 10:34:22.370 20264 20264 E AndroidRuntime: at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2252)
11-17 10:34:22.370 20264 20264 E AndroidRuntime: at android.app.ActivityThread.access$800(ActivityThread.java:139)
11-17 10:34:22.370 20264 20264 E AndroidRuntime: at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1210)
11-17 10:34:22.370 20264 20264 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:102)
11-17 10:34:22.370 20264 20264 E AndroidRuntime: at android.os.Looper.loop(Looper.java:136)
11-17 10:34:22.370 20264 20264 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:5028)
11-17 10:34:22.370 20264 20264 E AndroidRuntime: at java.lang.reflect.Method.invokeNative(Native Method)
11-17 10:34:22.370 20264 20264 E AndroidRuntime: at java.lang.reflect.Method.invoke(Method.java:515)
11-17 10:34:22.370 20264 20264 E AndroidRuntime: at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:791)
11-17 10:34:22.370 20264 20264 E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:607)
11-17 10:34:22.370 20264 20264 E AndroidRuntime: at dalvik.system.NativeStart.main(Native Method)
```

**Comment by messense** [comment]
Turns out it's a problem with multiple dex. I forgot to add the following `attachBaseContext` override code:

```java
public class MyApplication extends SomeOtherApplication {
  @Override
  protected void attachBaseContext(Context base) {
     super.attachBaseContext(context);
     Multidex.install(this);
  }
}
```

https://developer.android.com/studio/build/multidex.html#mdex-gradle

**Comment by SudoPlz** [comment]
Oh my God @messense you're a beast man, that fixed it..!!! Ok I literally have NO idea why that worked, would you mind explaining?

**Comment by TestIntegrations** [comment]
I am really glad that everything is working now 🎉

@SudoPlz @messense Thank you so much for your awesome contribution!

**Comment by NadineMansour** [comment]
I am really glad that everything is working now 🎉

@SudoPlz @messense Thank you so much for your awesome contribution!
